conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/celeba_128_three_resized/

measurement:
  operator:
    name: heat_blur
    intensity: 4.0

  noise:
    name: gaussian
    sigma: 0.1
