#!/usr/bin/env bash
# Regenerate the Gaussian report figures from the (updated) recon dirs.
# Uses free GPU cuda:1 for LPIPS in the figure headers. Run after rerun_ihdm_full.sh.
# Motion figures are regenerated by rerun_motion_reflect.sh (reflect-CG); defocus by its own wave.
set -u
cd "$(dirname "$0")/.."
DEV=cuda:1
MF="python scripts/make_figure.py --device $DEV --rows 4"

# ---- Gaussian (DCT), 3 noise levels : Clean|Obs|TV|cold+HQS|IHDM+HQS|DPS ----
gauss () {  # $1 dir  $2 outname  $3 title
  $MF --clean results/$1/clean --obs results/$1/observation \
    --recon "TV"=results/$1/tv_hqs/recon \
    --recon "cold+HQS"=results/$1/cold_hqs/recon \
    --recon "IHDM+HQS"=results/$1/ihdm_hqs/recon \
    --recon "DPS"=results/$1/dps/heat_blur/recon \
    --title "$3" --out results/$1/$2
}
gauss gaussian        figure_gaussian.png "Gaussian deblur (sigma=4, noise=0.05) - held-out CelebA-HQ 256"
gauss gaussian_n0p10  figure.png          "Gaussian deblur (sigma=4, noise=0.10) - held-out CelebA-HQ 256"
gauss gaussian_n0p20  figure.png          "Gaussian deblur (sigma=4, noise=0.20) - held-out CelebA-HQ 256"

echo "=== figures regenerated ==="
ls -la results/gaussian/figure_gaussian.png
