#!/usr/bin/env bash
# Re-run the Gaussian IHDM+HQS experiments used in the report with the full 211M checkpoint.
# Gaussian (DCT), 3 noise levels. Motion is regenerated by rerun_motion_reflect.sh (reflect-CG),
# defocus by deblur.py restore --operator defocus.
set -u
cd "$(dirname "$0")/.."
CKPT=checkpoint/ihdm/ihdm_ffhq256_full.pth
CFG=img_size_256_full
COMMON="--prior ihdm --ckpt $CKPT --ihdm_config $CFG --image_size 256 --n 16"
mkdir -p results/rerun_logs

# Gaussian, DCT, restore.py --solver hqs. sigma_y matched to observation noise.
CUDA_VISIBLE_DEVICES=0 python scripts/deblur.py restore --operator gaussian $COMMON \
  --clean_dir results/gaussian/clean --observation_dir results/gaussian/observation \
  --blur_sigma 4 --sigma_y 0.05 --device cuda:0 \
  --out results/gaussian/ihdm_hqs > results/rerun_logs/g05.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 python scripts/deblur.py restore --operator gaussian $COMMON \
  --clean_dir results/gaussian_n0p10/clean --observation_dir results/gaussian_n0p10/observation \
  --blur_sigma 4 --sigma_y 0.10 --device cuda:0 \
  --out results/gaussian_n0p10/ihdm_hqs > results/rerun_logs/g10.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 python scripts/deblur.py restore --operator gaussian $COMMON \
  --clean_dir results/gaussian_n0p20/clean --observation_dir results/gaussian_n0p20/observation \
  --blur_sigma 4 --sigma_y 0.20 --device cuda:0 \
  --out results/gaussian_n0p20/ihdm_hqs > results/rerun_logs/g20.log 2>&1 &
wait
echo "=== gaussian done ==="
echo "=== RESULT LINES ==="
grep -h "gaussian-HQS" results/rerun_logs/*.log
